### ISSUE TITLE
Missing file `map_array_slices_upfront.f90`

### ISSUE THREAD

**Issue by dmcdougall** [LLNL/FGPU#2]
Commit e0cdfe61e0c8e45210077606e1d40a367a6cc397 removed file `daxpy_map_array_slices_inline.f90`, but the patch in the makefile implies that the intent was to rename it rather than remove it.

Is my understanding correct?

**Comment by aaroncblack** [comment]
Hi @dmcdougall,
daxpy_map_array_slices_inline.f90 was renamed to map_array_slices.F90.

However... I'm seeing that map_array_slices_upfront.f90 is missing, I had not intended to delete that but to rename it.  (guessing that this is what you noticed ).

I'll fix that.

**Comment by aaroncblack** [comment]
Thanks for noticing the issue.  I looked over that old example and ended up removing it, as the current two examples encapsulate the common streaming+solve operation our codes are doing.

**Comment by dmcdougall** [comment]
Thanks.
